### ISSUE TITLE
Script error when receiving messages

### ISSUE THREAD

**Issue by SENSEI-Matt** [dudewheresmycode/node-iridium-sbd#3]
I am getting a script error relating to received messages. It looks like the 'mailboxCheck' needs to include a callback and pass it to 'sendMessage'. I have modified the index.js file and added a callback and this has resolved it. The error I received was:

/node_modules/iridium-sbd/index.js:558
Oct 04 11:05:09 gateway node[1915]:                                     callback(err, momsn);
Oct 04 11:05:09 gateway node[1915]:                                     ^
Oct 04 11:05:09 gateway node[1915]: TypeError: callback is not a function
Oct 04 11:05:09 gateway node[1915]:     at /node_modules/iridium-sbd/index.js:558:23
Oct 04 11:05:09 gateway node[1915]:     at df (/node_modules/iridium-sbd/index.js:604:10)
Oct 04 11:05:09 gateway node[1915]:     at SerialPort.<anonymous> (/node_modules/iridium-sbd/index.js:363:14)
Oct 04 11:05:09 gateway node[1915]:     at emitOne (events.js:116:13)
Oct 04 11:05:09 gateway node[1915]:     at SerialPort.emit (events.js:211:7)
Oct 04 11:05:09 gateway node[1915]:     at /node_modules/iridium-sbd/index.js:303:22
Oct 04 11:05:09 gateway node[1915]:     at Array.forEach (<anonymous>)
Oct 04 11:05:09 gateway node[1915]:     at SerialPort.readSBD (/node_modules/iridium-sbd/index.js:302:16)
Oct 04 11:05:09 gateway node[1915]:     at SerialPort._emitData (/node_modules/serialport/lib/serialport.js:313:18)
Oct 04 11:05:09 gateway node[1915]:     at SerialPort.<anonymous> (/node_modules/serialport/lib/serialport.js:293:14)

**Comment by zafrirron** [comment]
same here! 
can you please specify the fix location?

thanks

**Comment by SENSEI-Matt** [comment]
You need to edit the /node_modules/iridium-sbd/index.js file and change the mailboxCheck function. It's on around line 130. Just add the callback as a parameter and then pass it through to sendMessage.

mailboxCheck: function(callback) {
	    if (iridium.lock) {
	      iridium.pending++;
	    } else {
	      iridium.sendMessage("",callback);
	    }
	},

**Comment by zafrirron** [comment]
thanks @SENSEI-Matt 

Jus to make sure I guess you also modified the mailboxCheck calling method (since the readme file shows calling to mailboxCheck gets no params.....so I'm getting other errors.

thx

**Comment by SENSEI-Matt** [comment]
Thats right. Anywhere you call the mailboxCheck function you will need to pass a callback function.
